## Review Exercises

In [4]:
import numpy as np

p1= np.array([1,0])
p2 = np.array([0,1])

M = np.array([p1,p2]).T
M


array([[1, 0],
       [0, 1]])

In [5]:
B = (10, np.array((11,11)))
S = (10, np.array((20,5)))

M = np.array((B[1],S[1])).T

## don't know about how to define if it is invertible



In [7]:
K = 15

C1 = np.maximum (S[1]-K,0)

phi = np.linalg.solve ( M, C1)

C0 = np.dot(phi, (B[0], S[0]))

phi, C0

(array([-0.15151515,  0.33333333]), np.float64(1.8181818181818183))

## Exercise

In [13]:
M0 = np.array((B[0],S[0]))

phi2 = np.linalg.solve(M.T, M0)

M0_check = np.dot(M.T, phi2)
M0_check ==M0

array([ True,  True])

In [18]:
i =( B[1][0] - B[0]) / B[0]

# S0 *(1+i) = EQ(S1)
q = (S[0]*(1+i)-S[1][1]) / (S[1][0]-S[1][1])
Q = (q, 1-q)

V0 = np.dot(Q, C1) / (1+i)

if np.allclose(V0,C0):
    print("The same")
else:
    print("Not the same")
    


The same


In [21]:
# assume C0 now is lower
K_new = 17
C1_new = np.maximum ( S[1] - K_new, 0)
phi_new = np.linalg.solve (M, C1_new)

C0_new = np.dot(phi_new, (B[0], S[0]))

if C0_new < C0:
    print("buy C0_new and sell replicated C0 using B, S ")
else:
    print("sell C0_new and buy replicated C0 using B, S ")


np.float64(1.0909090909090908)

## Capstone Task

In [22]:
def port(M, M0, C1):

    phi = np.linalg.solve(M, C1)
    C0 = np.dot(phi,M0)

    return phi, C0



In [24]:
## test

B = (10.0, np.array((11.0, 11.0)))
S = (10.0, np.array((20.0, 5.0)))

M = np.array((B[1], S[1])).T
M0 = np.array((B[0], S[0]))

K = 15
C1 = np.maximum(S[1] - K, 0)

phi, C0 = port(M, M0, C1)
phi, C0

(array([-0.15151515,  0.33333333]), np.float64(1.8181818181818183))

In [28]:

M_sin = np.array(([11,20],[11+0.000000000000001, 20+0.000000000000001]))
C1 = np.array((5,0))

phi_ori = np.linalg.solve(M_sin, C1)
# phi_comp = np.linalg.lstsq(M_sin,C1)  ## why this doesn't work? the following is corrected by chatGPT

phi_comp, residuals, rank, s = np.linalg.lstsq(M_sin, C1, rcond=None)

check_ori = np.linalg.norm(np.dot(M_sin , phi_ori) -C1)
check_comp = np.linalg.norm(np.dot(M_sin, phi_comp) - C1)

check_ori, check_comp

(np.float64(2.5275343226286986), np.float64(3.5355339059327378))